### ISSUE TITLE
working perfectly on windows 10

### ISSUE THREAD

**Issue by carmanzhang** [kumakichi/Deepl-linux-electron#13]
I just tested this repo on Windows 10, after building with the command `yarn dist:dir`, I found the `dist\win-unpacked` can successfully be generated, and the built binary `Deepl-Linux-Electron.exe` can also run perfectly, and also the shortcuts binding function. So, is there a need to rename the repo to Deepl-electron and release the Deepl Windows desktop binary as well in follow-up package releases?

![image](https://github.com/kumakichi/Deepl-linux-electron/assets/15645752/4d7656b4-6e7a-4ca6-9b8c-2645b4a86bc0)

![image](https://github.com/kumakichi/Deepl-linux-electron/assets/15645752/1554eb86-2217-4a61-baa6-b1dcdaadaae5)

**Comment by kumakichi** [comment]
Theoretically, this repository can be used in macOS and windows because of electron. But both of them have official clients, this repository is just to cope with the problem that linux has no official client. So, I prefer to keep the previous name for now.
