### ISSUE TITLE
Tray Icon to dark to clearly be seen in tray

### ISSUE THREAD

**Issue by doiftrue** [kumakichi/Deepl-linux-electron#4]
![2022-01-18_02-41](https://user-images.githubusercontent.com/15121552/149839910-3a075b11-01bb-434f-a20e-de65fe3fde45.png)

Replace in with this one please! It suite for light and dark themes.

![tray-icon](https://user-images.githubusercontent.com/15121552/149839988-bf15fd6a-db30-43ac-b6b1-2bca56f10a38.png)

Here is SVG version [tray-icon.zip](https://github.com/kumakichi/Deepl-linux-electron/files/7884789/tray-icon.zip)

**Comment by kumakichi** [comment]
Thanks

please use v1.1.1 : https://github.com/kumakichi/Deepl-linux-electron/releases/tag/v1.1.1
